# Supabase configuration for Movax ERP / POS
project_id = "bkbcgndzsfylwsinxwbb"

[api]
enabled = true
port = 54321
schemas = ["public", "private", "migration", "audit"]
extra_search_path = ["public", "extensions"]

[db]
port = 54322
shadow_port = 54320
major_version = 15

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://127.0.0.1:5173", "http://localhost:5173"]
jwt_expiry = 28800
enable_signup = false

[auth.email]
enable_signup = false
double_confirm_changes = true
enable_confirmations = false
